Repository http-rs/tide, pull requests merged in 2020-07, with the labels that each got.

#598 return a result from sse sender
  Cargo.toml
  examples/sse.rs
  src/sse/mod.rs
  src/sse/sender.rs
Labels: bug

#570 Rework middleware to receive Response directly, add optional errors to Response
  examples/error_handling.rs
  examples/middleware.rs
  src/cookies/middleware.rs
  src/endpoint.rs
  src/fs/serve_dir.rs
  src/log/middleware.rs
  src/middleware.rs
  src/redirect.rs
  src/response.rs
  src/route.rs
  src/router.rs
  src/security/cors.rs
  src/server.rs
  src/utils.rs
  tests/function_middleware.rs
  tests/nested.rs
  tests/response.rs
  tests/route_middleware.rs
Labels: blocked, design, enhancement

#601 introduce an extension trait for testing servers
  tests/nested.rs
  tests/response.rs
  tests/route_middleware.rs
  tests/test_utils.rs
  tests/wildcard.rs
Labels: enhancement
